---
- hosts: all
  become: yes
  tasks:
  - name: Install packages that allow apt to be used over HTTPS
    apt:
      name: "{{ packages }}"
      state: present
      update_cache: yes
    vars:
      packages:
      - apt-transport-https
      - ca-certificates
      - curl
      - gnupg
      - git

# install with `ansible-galaxy collection install community.general`
  - name: Install microk8s with option classic
    community.general.snap:
      name: microk8s
      classic: yes

  - name: Creates root ssh directory
    file:
      path: /root/.ssh
      state: directory
      owner: root
      group: root
      mode: 0700

  - name: Add authorized key for root
    copy:
      src: credentials/authorized_keys
      dest: /root/.ssh/authorized_keys
      owner: root
      group: root
      mode: 0600
