---
- hosts: all
  become: yes
  tasks:
  # install with `ansible-galaxy collection install community.general`
  - name: Install microk8s with option classic
    community.general.snap:
      name: microk8s
      classic: yes

  - name: Create honeybee group
    ansible.builtin.group:
      name: honeybee
      state: present

  - name: Add Honeybee user
    user:
      name: honeybee
      groups: honeybee, microk8s

  - name: Change ownership of honeybee .kube folder
    file:
      path: /home/honeybee/.kube
      owner: honeybee
      group: honeybee
      recurse: yes

  - name: Creates honeybee ssh directory
    file:
      path: /home/honeybee/.ssh
      state: directory
      owner: honeybee
      group: honeybee
      mode: 0700

  - name: Add authorized key for honeybee
    copy:
      src: credentials/authorized_keys
      dest: /home/honeybee/.ssh/authorized_keys
      owner: honeybee
      group: honeybee
      mode: 0600
